using System.IO;
using System.Linq;
using UnityEditor;
using UnityEditor.Build;
using UnityEditor.Build.Reporting;
using UnityEngine;

/// <summary>
/// Embeds the autograder key into player builds. Before a build, writes GeneratedPath from
/// the key file at Utilities.KeyFilePath; after the build, or on the next editor load when a
/// build was interrupted, deletes it. Without a valid key file the build continues with score
/// codes disabled.
/// </summary>
[InitializeOnLoad]
public class AutograderKeyBuildStep : IPreprocessBuildWithReport, IPostprocessBuildWithReport
{
    /// <summary>
    /// Source file implementing Utilities.SetKey, present only while a player build runs.
    /// </summary>
    public const string GeneratedPath = "Assets/Scripts/Static/AutograderKey.Generated.cs";

    static AutograderKeyBuildStep()
    {
        if (!BuildPipeline.isBuildingPlayer)
        {
            EditorApplication.delayCall += AutograderKeyBuildStep.RemoveGenerated;
        }
    }

    /// <inheritdoc />
    public int callbackOrder { get { return 0; } }

    /// <summary>
    /// True if the key file holds a valid key, so the next player build embeds it.
    /// </summary>
    public static bool HasValidKey { get { return AutograderKeyBuildStep.ReadKey() != null; } }

    /// <inheritdoc />
    public void OnPreprocessBuild(BuildReport report)
    {
        byte[] key = AutograderKeyBuildStep.ReadKey();
        if (key == null)
        {
            Debug.LogWarning($"No valid autograder key at {Utilities.KeyFilePath}; score codes are disabled in this build.");
            return;
        }

        string bytes = string.Join(", ", key.Select(b => $"0x{b:X2}"));
        File.WriteAllText(AutograderKeyBuildStep.GeneratedPath,
            "// Generated by AutograderKeyBuildStep for the current build; deleted afterwards.\n" +
            "public static partial class Utilities\n" +
            "{\n" +
            "    static partial void SetKey(ref byte[] key)\n" +
            "    {\n" +
            $"        key = new byte[] {{ {bytes} }};\n" +
            "    }\n" +
            "}\n");
        AssetDatabase.ImportAsset(AutograderKeyBuildStep.GeneratedPath, ImportAssetOptions.ForceSynchronousImport);
    }

    /// <inheritdoc />
    public void OnPostprocessBuild(BuildReport report)
    {
        AutograderKeyBuildStep.RemoveGenerated();
    }

    private static byte[] ReadKey()
    {
        return File.Exists(Utilities.KeyFilePath) ? Utilities.ParseKeyHex(File.ReadAllText(Utilities.KeyFilePath)) : null;
    }

    private static void RemoveGenerated()
    {
        if (File.Exists(AutograderKeyBuildStep.GeneratedPath))
        {
            AssetDatabase.DeleteAsset(AutograderKeyBuildStep.GeneratedPath);
        }
    }
}
